<<<<<<< HEAD
=======

>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace CajaPopular
{
    using System;
    using System.Collections.Generic;
    
    public partial class aval
    {
        public aval()
        {
            this.rel_solicitante_aval = new HashSet<rel_solicitante_aval>();
        }
    
        public int uid { get; set; }
        public Nullable<int> id_persona { get; set; }
        public string num_socio { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual ICollection<rel_solicitante_aval> rel_solicitante_aval { get; set; }
    }
=======

namespace CajaPopular
{

using System;
    using System.Collections.Generic;
    
public partial class aval
{

    public aval()
    {

        this.rel_solicitante_aval = new HashSet<rel_solicitante_aval>();

    }


    public int uid { get; set; }

    public Nullable<int> id_persona { get; set; }

    public string num_socio { get; set; }



    public virtual persona persona { get; set; }

    public virtual ICollection<rel_solicitante_aval> rel_solicitante_aval { get; set; }

}

>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
}
