<<<<<<< HEAD
=======

>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CajaPopular
{
    using System;
    using System.Collections.Generic;
    
    public partial class balance
    {
        [Key, Column(Order=0)]
        public int id_solicitante { get; set; }
        [Key, Column(Order = 1)]
        public int factura { get; set; }
        [Key, Column(Order = 2)]
        public int num_documento { get; set; }
        public string descripcion { get; set; }
        public decimal cantidad { get; set; }
        public System.DateTime fecha_captura { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public int capturista { get; set; }
        public bool borrado { get; set; }
        public bool cubierto { get; set; }
    
        public virtual solicitante solicitante { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual persona persona { get; set; }

        public virtual List<persona> listaper { get; set; }
        public virtual List<solicitante> listasol { get; set; }
        public object PrimaryKey { get; set; }
    }
=======

namespace CajaPopular
{

using System;
    using System.Collections.Generic;
    
public partial class balance
{

    public int id_solicitante { get; set; }

    public int factura { get; set; }

    public int num_documento { get; set; }

    public string descripcion { get; set; }

    public Nullable<decimal> cantidad { get; set; }

    public Nullable<System.DateTime> fecha_captura { get; set; }

    public Nullable<System.DateTime> fecha_vencimiento { get; set; }

    public Nullable<System.DateTime> fecha_pago { get; set; }

    public Nullable<int> capturista { get; set; }

    public Nullable<bool> borrado { get; set; }

    public Nullable<bool> cubierto { get; set; }



    public virtual solicitante solicitante { get; set; }

    public virtual usuario usuario { get; set; }

}

>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
}
