<<<<<<< HEAD
﻿//------------------------------------------------------------------------------
=======
﻿

//------------------------------------------------------------------------------
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
=======

>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
