<<<<<<< HEAD
=======

>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace CajaPopular
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.balances = new HashSet<balance>();
        }
    
        public int uid { get; set; }
        public int id_persona { get; set; }
        public string departamento { get; set; }
        public string usuario1 { get; set; }
        public string contraseña { get; set; }
        public string grupo { get; set; }
        public string rol { get; set; }
    
        public virtual ICollection<balance> balances { get; set; }
    }
=======

namespace CajaPopular
{

using System;
    using System.Collections.Generic;
    
public partial class usuario
{

    public usuario()
    {

        this.balances = new HashSet<balance>();

    }


    public int uid { get; set; }

    public Nullable<int> id_persona { get; set; }

    public string departamento { get; set; }

    public string usuario1 { get; set; }

    public string contraseña { get; set; }

    public string grupo { get; set; }

    public string rol { get; set; }



    public virtual ICollection<balance> balances { get; set; }

}

>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
}
